<a href="https://colab.research.google.com/github/Vanessa-Flores-Hernandez/Probabilidad/blob/main/Unidad1/Practica3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Probabilida y estadistica**

## **Unidad 1**

### **Practica 3. Tabla de frecuencias y reglas de Sturges...**

### Docente: *Dr. Jose Gabriel Rodriguez Rivas*

### Alumno: Vanessa Mariam Flores Hernandez

In [8]:
# basado en el libro estadistica para administracion pagina 12
# creamos una lista vacia que representa la edad de 100 personas
import random
edades = []
# hacemos un ciclo para generar 100 numeros aleatorios que representen la edad de las personas
for i in range(100):
  # generamos un numero aleatorio con la funcion randint y lo guardamos en la variable
  # numero_aleatorio
  numero_aleatorio = random.randint( 18, 70)
  # agregamos el numero aleatorio a la lista de valores
  edades.append(numero_aleatorio)
print(edades)

[67, 23, 20, 47, 37, 35, 20, 20, 66, 33, 22, 50, 33, 53, 64, 53, 51, 68, 37, 27, 46, 56, 65, 69, 34, 69, 49, 22, 37, 39, 26, 20, 52, 50, 48, 28, 60, 57, 59, 51, 52, 63, 25, 27, 50, 55, 46, 69, 29, 64, 26, 65, 64, 34, 31, 61, 30, 24, 19, 47, 33, 38, 51, 19, 61, 52, 42, 30, 18, 36, 56, 24, 45, 35, 37, 51, 41, 64, 29, 61, 50, 68, 18, 22, 40, 65, 61, 61, 63, 26, 34, 47, 19, 21, 19, 26, 22, 45, 40, 34]

In [9]:
import pandas as pd

In [10]:
# crear un DataFrame de pandas con los numeros aleatorios
df = pd.DataFrame(edades, columns = ["Edad"])
df.head()

   Edad
0    67
1    23
2    20
3    47
4    37

In [11]:
# calcular la tabla de distribucion de frecuencias
tabla_frecuencias = df["Edad"].value_counts().reset_index()
tabla_frecuencias.columns = ["Edad", "Frecuencia"]
tabla_frecuencias = tabla_frecuencias.sort_values(by = "Edad")

# imprimir la tabñla de distribucion de frecuencias
print("Tabla de distribucion de frecuencias: ")
tabla_frecuencias

Tabla de distribucion de frecuencias:

    Edad  Frecuencia
16    18           2
7     19           4
5     20           4
45    21           1
4     22           4
28    23           1
25    24           2
39    25           1
6     26           4
27    27           2
37    28           1
23    29           2
26    30           2
40    31           1
10    33           3
8     34           4
19    35           2
42    36           1
1     37           4
41    38           1
35    39           1
20    40           2
44    41           1
43    42           1
15    45           2
21    46           2
11    47           3
34    48           1
36    49           1
9     50           4
3     51           4
13    52           3
18    53           2
38    55           1
24    56           2
33    57           1
31    59           1
32    60           1
0     61           5
22    63           2
2     64           4
12    65           3
30    66           1
29    67           1
17    68           2
14    69           3

Calcular la frecuencia relativa

In [12]:
tabla_frecuencias["Frec Relativa"] = tabla_frecuencias["Frecuencia"] / 100
tabla_frecuencias

    Edad  Frecuencia  Frec Relativa
16    18           2           0.02
7     19           4           0.04
5     20           4           0.04
45    21           1           0.01
4     22           4           0.04
28    23           1           0.01
25    24           2           0.02
39    25           1           0.01
6     26           4           0.04
27    27           2           0.02
37    28           1           0.01
23    29           2           0.02
26    30           2           0.02
40    31           1           0.01
10    33           3           0.03
8     34           4           0.04
19    35           2           0.02
42    36           1           0.01
1     37           4           0.04
41    38           1           0.01
35    39           1           0.01
20    40           2           0.02
44    41           1           0.01
43    42           1           0.01
15    45           2           0.02
21    46           2           0.02
11    47           3           0.03
34    48           1           0.01
36    49           1           0.01
9     50           4           0.04
3     51           4           0.04
13    52           3           0.03
18    53           2           0.02
38    55           1           0.01
24    56           2           0.02
33    57           1           0.01
31    59           1           0.01
32    60           1           0.01
0     61           5           0.05
22    63           2           0.02
2     64           4           0.04
12    65           3           0.03
30    66           1           0.01
29    67           1           0.01
17    68           2           0.02
14    69           3           0.03

Calcular la frecuencia porcentual

In [13]:
tabla_frecuencias["Frec Porcentual"] = tabla_frecuencias["Frecuencia"] / 100 * 100
tabla_frecuencias

    Edad  Frecuencia  Frec Relativa  Frec Porcentual
16    18           2           0.02              2.0
7     19           4           0.04              4.0
5     20           4           0.04              4.0
45    21           1           0.01              1.0
4     22           4           0.04              4.0
28    23           1           0.01              1.0
25    24           2           0.02              2.0
39    25           1           0.01              1.0
6     26           4           0.04              4.0
27    27           2           0.02              2.0
37    28           1           0.01              1.0
23    29           2           0.02              2.0
26    30           2           0.02              2.0
40    31           1           0.01              1.0
10    33           3           0.03              3.0
8     34           4           0.04              4.0
19    35           2           0.02              2.0
42    36           1           0.01              1.0
1     37           4           0.04              4.0
41    38           1           0.01              1.0
35    39           1           0.01              1.0
20    40           2           0.02              2.0
44    41           1           0.01              1.0
43    42           1           0.01              1.0
15    45           2           0.02              2.0
21    46           2           0.02              2.0
11    47           3           0.03              3.0
34    48           1           0.01              1.0
36    49           1           0.01              1.0
9     50           4           0.04              4.0
3     51           4           0.04              4.0
13    52           3           0.03              3.0
18    53           2           0.02              2.0
38    55           1           0.01              1.0
24    56           2           0.02              2.0
33    57           1           0.01              1.0
31    59           1           0.01              1.0
32    60           1           0.01              1.0
0     61           5           0.05              5.0
22    63           2           0.02              2.0
2     64           4           0.04              4.0
12    65           3           0.03              3.0
30    66           1           0.01              1.0
29    67           1           0.01              1.0
17    68           2           0.02              2.0
14    69           3           0.03              3.0

Calcular la frecuencia acumulada